[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ManifestPath,
    [Parameter(Mandatory = $true)]
    [string]$PayloadPath,
    [Parameter(Mandatory = $true)]
    [string]$PfxPath,
    [string]$PasswordEnv
)

$ErrorActionPreference = 'Stop'

function Hex-Lower([byte[]]$Bytes) {
    -join ($Bytes | ForEach-Object { $_.ToString('x2') })
}

function Utf8-NoBom([string]$Value) {
    return ,([System.Text.UTF8Encoding]::new($false).GetBytes($Value))
}

$certificate = $null
$securePassword = $null
try {
    if (-not [System.IO.File]::Exists($ManifestPath) -or -not [System.IO.File]::Exists($PfxPath)) {
        throw 'CMS signing input is missing'
    }
    Add-Type -AssemblyName System.Security.Cryptography.Pkcs
    $flags = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::EphemeralKeySet
    if ([string]::IsNullOrWhiteSpace($PasswordEnv)) {
        $securePassword = Read-Host -Prompt 'PFX password (will not be echoed)' -AsSecureString
        $certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new(
            $PfxPath,
            $securePassword,
            $flags
        )
    } else {
        if (-not [System.Environment]::GetEnvironmentVariables().Contains($PasswordEnv)) {
            throw 'the named PFX password environment variable is missing'
        }
        $password = [System.Environment]::GetEnvironmentVariable($PasswordEnv)
        $certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new(
            $PfxPath,
            $password,
            $flags
        )
        $password = $null
    }
    if (-not $certificate.HasPrivateKey) {
        throw 'PFX does not contain a private key'
    }
    $hash = [System.Security.Cryptography.SHA256]::Create()
    try { $keyId = Hex-Lower ($hash.ComputeHash($certificate.RawData)) } finally { $hash.Dispose() }

    $manifest = Get-Content -LiteralPath $ManifestPath -Raw | ConvertFrom-Json
    $manifest.signature.keyId = $keyId
    $manifest.signature.value = ''
    $unsignedJson = $manifest | ConvertTo-Json -Compress -Depth 20
    $domain = [System.Text.Encoding]::ASCII.GetBytes("VeriSilo engine package manifest v3`0")
    $unsignedBytes = Utf8-NoBom $unsignedJson
    $payload = [byte[]]::new($domain.Length + $unsignedBytes.Length)
    [System.Buffer]::BlockCopy($domain, 0, $payload, 0, $domain.Length)
    [System.Buffer]::BlockCopy($unsignedBytes, 0, $payload, $domain.Length, $unsignedBytes.Length)
    [System.IO.File]::WriteAllBytes($PayloadPath, $payload)

    $content = [System.Security.Cryptography.Pkcs.ContentInfo]::new($payload)
    $cms = [System.Security.Cryptography.Pkcs.SignedCms]::new($content, $true)
    $signer = [System.Security.Cryptography.Pkcs.CmsSigner]::new(
        [System.Security.Cryptography.Pkcs.SubjectIdentifierType]::IssuerAndSerialNumber,
        $certificate
    )
    $signer.DigestAlgorithm = [System.Security.Cryptography.Oid]::new('2.16.840.1.101.3.4.2.1')
    $cms.ComputeSignature($signer)
    $manifest.signature.value = [Convert]::ToBase64String($cms.Encode())
    $finalJson = $manifest | ConvertTo-Json -Depth 20
    [System.IO.File]::WriteAllBytes($ManifestPath, (Utf8-NoBom ($finalJson + "`n")))

    # Re-open the generated bytes and verify the exact payload/CMS locally.
    $check = Get-Content -LiteralPath $ManifestPath -Raw | ConvertFrom-Json
    $check.signature.value = ''
    $checkJson = $check | ConvertTo-Json -Compress -Depth 20
    $checkUnsigned = Utf8-NoBom $checkJson
    $checkPayload = [byte[]]::new($domain.Length + $checkUnsigned.Length)
    [System.Buffer]::BlockCopy($domain, 0, $checkPayload, 0, $domain.Length)
    [System.Buffer]::BlockCopy($checkUnsigned, 0, $checkPayload, $domain.Length, $checkUnsigned.Length)
    if (-not [System.Linq.Enumerable]::SequenceEqual($payload, $checkPayload)) {
        throw 'CMS payload changed while writing the manifest'
    }
    $encoded = [Convert]::FromBase64String((Get-Content -LiteralPath $ManifestPath -Raw | ConvertFrom-Json).signature.value)
    $verifyContent = [System.Security.Cryptography.Pkcs.ContentInfo]::new($checkPayload)
    $verifyCms = [System.Security.Cryptography.Pkcs.SignedCms]::new($verifyContent, $true)
    $verifyCms.Decode($encoded)
    if (
        $verifyCms.SignerInfos.Count -ne 1 -or
        $verifyCms.SignerInfos[0].DigestAlgorithm.Value -ne '2.16.840.1.101.3.4.2.1'
    ) {
        throw 'CMS output is not one SHA-256 signer'
    }
    $verifyCms.CheckSignature($true)
    Write-Output 'CMS manifest signature created and rechecked.'
}
catch {
    throw "CMS manifest signing failed: $($_.Exception.Message)"
}
finally {
    if ($null -ne $certificate) {
        $certificate.Dispose()
    }
    if ($null -ne $securePassword) {
        $securePassword.Dispose()
    }
}
